# Generated by Django 4.1.1 on 2022-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=255)),
                ('discription_site', models.CharField(max_length=255)),
                ('logo_site', models.ImageField(upload_to='logo/')),
                ('facebook_site', models.URLField()),
                ('twitter_site', models.URLField()),
                ('instagram_site', models.URLField()),
                ('youtube_site', models.URLField()),
            ],
        ),
    ]
